<?php

namespace ContainerPV6TG4g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_QoRVXuvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.QoRVXuv' shared service.
     *
     * @return \App\Entity\Todo
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\TodoController::showAction()": the $todo argument is type-hinted with the non-existent class or interface: "App\\Entity\\Todo".');
    }
}
