<?php

namespace ContainerPV6TG4g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LX8I4m5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lX8I4m5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lX8I4m5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'todo' => ['privates', '.errored.QoRVXuv', NULL, 'Cannot determine controller argument for "App\\Controller\\TodoController::showAction()": the $todo argument is type-hinted with the non-existent class or interface: "App\\Entity\\Todo".'],
        ], [
            'todo' => '?',
        ]);
    }
}
