<?php

namespace ContainerPV6TG4g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddTagCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\AddTagCommand' shared autowired service.
     *
     * @return \App\Command\AddTagCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/AddTagCommand.php';

        $container->privates['App\\Command\\AddTagCommand'] = $instance = new \App\Command\AddTagCommand(($container->services['doctrine'] ?? self::getDoctrineService($container)));

        $instance->setName('app:add-tag');
        $instance->setDescription('Add a tag to a todo (both must exist already)');

        return $instance;
    }
}
