<?php

namespace ContainerPV6TG4g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDelTodoCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\DelTodoCommand' shared autowired service.
     *
     * @return \App\Command\DelTodoCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/DelTodoCommand.php';

        $container->privates['App\\Command\\DelTodoCommand'] = $instance = new \App\Command\DelTodoCommand(($container->services['doctrine'] ?? self::getDoctrineService($container)));

        $instance->setName('app:del-todo');
        $instance->setDescription('Delete one todo');

        return $instance;
    }
}
