<?php

namespace ContainerPV6TG4g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewTagCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\NewTagCommand' shared autowired service.
     *
     * @return \App\Command\NewTagCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/NewTagCommand.php';

        $container->privates['App\\Command\\NewTagCommand'] = $instance = new \App\Command\NewTagCommand(($container->services['doctrine'] ?? self::getDoctrineService($container)));

        $instance->setName('app:new-tag');
        $instance->setDescription('Creates a new tag');

        return $instance;
    }
}
