<?php

namespace ContainerPV6TG4g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewTodoCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\NewTodoCommand' shared autowired service.
     *
     * @return \App\Command\NewTodoCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/NewTodoCommand.php';

        $container->privates['App\\Command\\NewTodoCommand'] = $instance = new \App\Command\NewTodoCommand(($container->services['doctrine'] ?? self::getDoctrineService($container)));

        $instance->setName('app:new-todo');
        $instance->setDescription('Creates a new todo');

        return $instance;
    }
}
