<?php

namespace ContainerKWjx46T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddTagCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\AddTagCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\AddTagCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:add-tag', [], 'Add a tag to a todo (both must exist already)', false, #[\Closure(name: 'App\\Command\\AddTagCommand')] fn (): \App\Command\AddTagCommand => ($container->privates['App\\Command\\AddTagCommand'] ?? $container->load('getAddTagCommandService')));
    }
}
