<?php

namespace ContainerKWjx46T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDelTodoCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\DelTodoCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\DelTodoCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:del-todo', [], 'Delete one todo', false, #[\Closure(name: 'App\\Command\\DelTodoCommand')] fn (): \App\Command\DelTodoCommand => ($container->privates['App\\Command\\DelTodoCommand'] ?? $container->load('getDelTodoCommandService')));
    }
}
