<?php

namespace ContainerKWjx46T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getListTagsCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\ListTagsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\ListTagsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:list-tags', [], 'Add a short description for your command', false, #[\Closure(name: 'App\\Command\\ListTagsCommand')] fn (): \App\Command\ListTagsCommand => ($container->privates['App\\Command\\ListTagsCommand'] ?? $container->load('getListTagsCommandService')));
    }
}
