<?php

namespace ContainerKWjx46T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getListactiveTodosCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ListactiveTodosCommand' shared autowired service.
     *
     * @return \App\Command\ListactiveTodosCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ListactiveTodosCommand.php';

        $container->privates['App\\Command\\ListactiveTodosCommand'] = $instance = new \App\Command\ListactiveTodosCommand(($container->services['doctrine'] ?? self::getDoctrineService($container)));

        $instance->setName('app:list-active-todos');
        $instance->setDescription('List the active todos');

        return $instance;
    }
}
