<?php

namespace ContainerKWjx46T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewTagCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\NewTagCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\NewTagCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:new-tag', [], 'Creates a new tag', false, #[\Closure(name: 'App\\Command\\NewTagCommand')] fn (): \App\Command\NewTagCommand => ($container->privates['App\\Command\\NewTagCommand'] ?? $container->load('getNewTagCommandService')));
    }
}
