<?php

namespace ContainerKWjx46T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdateTodoCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\UpdateTodoCommand' shared autowired service.
     *
     * @return \App\Command\UpdateTodoCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/UpdateTodoCommand.php';

        $container->privates['App\\Command\\UpdateTodoCommand'] = $instance = new \App\Command\UpdateTodoCommand(($container->services['doctrine'] ?? self::getDoctrineService($container)));

        $instance->setName('app:update-todo');
        $instance->setDescription('Updates a tod');

        return $instance;
    }
}
