<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXlT1YK8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXlT1YK8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXlT1YK8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXlT1YK8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXlT1YK8\App_KernelDevDebugContainer([
    'container.build_hash' => 'XlT1YK8',
    'container.build_id' => '4503d933',
    'container.build_time' => 1748110253,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXlT1YK8');
