<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2ifyTOB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2ifyTOB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2ifyTOB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2ifyTOB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2ifyTOB\App_KernelDevDebugContainer([
    'container.build_hash' => '2ifyTOB',
    'container.build_id' => '65c5bf15',
    'container.build_time' => 1746728839,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container2ifyTOB');
