<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBA6RFHV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBA6RFHV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBA6RFHV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBA6RFHV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBA6RFHV\App_KernelDevDebugContainer([
    'container.build_hash' => 'BA6RFHV',
    'container.build_id' => '80cde983',
    'container.build_time' => 1747863675,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBA6RFHV');
