<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\TodoController::indexAction'], [], [['text', '/todo/']], [], [], []],
    'todo_list' => [[], ['_controller' => 'App\\Controller\\TodoController::listAction'], [], [['text', '/todo/list']], [], [], []],
    'todo_index' => [[], ['_controller' => 'App\\Controller\\TodoController::listAction'], [], [['text', '/todo/index']], [], [], []],
    'todo_show' => [['id'], ['_controller' => 'App\\Controller\\TodoController::showAction'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/todo']], [], [], []],
    'App\Controller\TodoController::indexAction' => [[], ['_controller' => 'App\\Controller\\TodoController::indexAction'], [], [['text', '/todo/']], [], [], []],
    'App\Controller\TodoController::showAction' => [['id'], ['_controller' => 'App\\Controller\\TodoController::showAction'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/todo']], [], [], []],
];
