<?php

namespace ContainerER9WENE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getListTodosCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ListTodosCommand' shared autowired service.
     *
     * @return \App\Command\ListTodosCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ListTodosCommand.php';

        $container->privates['App\\Command\\ListTodosCommand'] = $instance = new \App\Command\ListTodosCommand(($container->services['doctrine'] ?? $container->load('getDoctrineService')));

        $instance->setName('app:list-todos');
        $instance->setDescription('Add a short description for your command');

        return $instance;
    }
}
